### ISSUE TITLE
issues with opening files in PhenoteFX

### ISSUE THREAD

**Issue by nicolevasilevsky** [pnrobinson/hphenote#24]
Hi @pnrobinson-
I downloaded the latest release of PhenoteFX, but it won't open any of the files.
These are my settings.
![image](https://user-images.githubusercontent.com/6722114/43216976-39bca144-8ff5-11e8-8cd3-8f6641fe3958.png)
Could you help troubleshoot?

When I try to open from MIM ID or just open a file, nothing loads.

Thanks!

**Comment by pnrobinson** [comment]
@nicolevasilevsky  can you try starting from the command line and sending me any messages that appear? PhenoteFX has been working stabiliy for me recently. I will do a new release right now, please try that, there have been lots of improvements.

**Comment by nicolevasilevsky** [comment]
I downloaded the new release and it is working now- thank you!
