### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kingmanzhang** [pnrobinson/hphenote#33]
exception when cancel choosing folder for annotation data

**Comment by kingmanzhang** [comment]
I will take care of it.

**Comment by kingmanzhang** [comment]
not sure why I cannot push a branch in. Do I have write privilege? (not sure how to check) @pnrobinson

**Comment by pnrobinson** [comment]
@kingmanzhang Was this issue resolved?

**Comment by kingmanzhang** [comment]
Yes. Close it now.
