### ISSUE TITLE
Frequency update bug encountered while updating OMIM:610443

### ISSUE THREAD

**Issue by LCCarmody** [pnrobinson/hphenote#34]
I am trying to add additional frequency info to OMIM:610443 for this ticket (https://github.com/obophenotype/human-phenotype-ontology/issues/4163).  There is already many of these terms listed from other sources but I am updating with a new PMID with frequency info.  
Tried adding microcephaly (which is already annotated to the disease, but I am adding a second time for frequency info). 
1st issue:  I added  the term manually using the standard gui feature. (I.e., I filled out Microcephaly, PCS, Frequency=5%, Source=PMID:18628315 .  Everything added to the entry EXCEPT frequency.  
Once the new entry had been added, I tried to update the frequency manually.  I have done it twice and no frequency info has been added.  Upon reviewing the list, it appears that '5%' frequency had been added to 'Short stature' and not 'microcephaly'.  @kingmanzhang @pnrobinson

**Comment by kingmanzhang** [comment]
The problem seems to be cell.getRow() return wrong row (not the row where mouse is clicked). I haven't figured out how to address this issue. @pnrobinson

**Comment by kingmanzhang** [comment]
done.
