### ISSUE TITLE
annotate one disease a time

### ISSUE THREAD

**Issue by kingmanzhang** [pnrobinson/hphenote#40]
I do not see the point letting user annotating multiple disease at once. Shall we enforce that only one disease file is opened and to be annotated? @pnrobinson

**Comment by pnrobinson** [comment]
I agree -- better to limit to one at a time.

**Comment by kingmanzhang** [comment]
okay. I am going to erase all annotations when a new file is opened.

**Comment by pnrobinson** [comment]
1+
