### ISSUE TITLE
new feature request

### ISSUE THREAD

**Issue by kingmanzhang** [pnrobinson/hphenote#45]
Leigh and I talked about some layout changes that can help curation:
1. get rid of Disease ID and Disease Name columns. Instead, show it as the title of the table. Also create a dropdown menu to select diseases for curation. 

2. The HPO tree is very useful, it should always be there. So shrink the table to the left and add the HPO tree on the right. 

3. Add last_edited by. 

@pnrobinson  comments?

**Comment by pnrobinson** [comment]
These sound like great ideas. Also, if we also import MONDO, in some cases we can use it to get a preferred disease name and replace the strings from OMIM, which are often unwieldly. Currently, last edited by gets added automatically if you modify an existing annotation -- this feature appears to be working, but it is difficult to see in the GUI. Perhaps it would also be good to make a function to view the current annotations in a more convenient way.

**Comment by pnrobinson** [comment]
This is now implemented, I will close this.
