### ISSUE TITLE
Minor issue in Fetch text mining tool v. 0.4.4: cancel button not working

### ISSUE THREAD

**Issue by LCCarmody** [pnrobinson/hphenote#47]
If you add text to the 'Text-mining analysis' window and hit 'Analyze!', the cancel button doesn't do anything.  The only way to get out that is to hit 'Add selected terms'.  If you don't want to add anything, you just don't select anything.  

Either remove the 'cancel' button or make it actually cancel.

**Comment by kingmanzhang** [comment]
done
