### ISSUE TITLE
Frequency row bug still there...

### ISSUE THREAD

**Issue by pnrobinson** [pnrobinson/hphenote#59]
I can reproduce it in entry OMIM:146255
I click on a certain frequency entry to update it but I get a different entry in the dialog.

**Comment by kingmanzhang** [comment]
I have not been able to reproduce the bug with this file. I suggest you look at the logger (trace) when you make a frequency update. The logger should output the index and content of the row that you are trying to make changes to. If this is not the row where you clicked the frequency cell, it means a error. I haven't been able to see a mismatch.  

```
[TRACE] 2019-01-04 13:05:14.316 [JavaFX Application Thread] (org.monarchinitiative.phenotefx.gui.main.PhenotePresenter:1273) - phenol row: OMIM:146255	HYPOPARATHYROIDISM, SENSORINEURAL DEAFNESS, AND RENAL DISEASE	HP:0002049	Proximal renal tubular acidosis								PMID:29663634	PCS	HPO:nvasilevsky[2018-08-02];HPO:nvasilevsky[2018-08-02]
[TRACE] 2019-01-04 13:05:14.316 [JavaFX Application Thread] (org.monarchinitiative.phenotefx.gui.main.PhenotePresenter:1274) - 12
```

**Comment by pnrobinson** [comment]
hmm, seems Ok now!
