### ISSUE TITLE
Add function to import local copy of HPO

### ISSUE THREAD

**Issue by pnrobinson** [pnrobinson/hphenote#6]
similar to HPO Workbench

**Comment by nicolevasilevsky** [comment]
I am still having issues importing the local copy of HPO to PhenoteFX. I have the latest release, and I re-ran the make file using the instructions [here](http://hpo-workbench.readthedocs.io/en/latest/latest.html). I am able to see the latest version of HPO in the HPO Workbench, but in PhenoteFX. In PhenoteFX, when I do Edit->Import local hp.obo file, and import my local file, I still don't see the newest ontology terms I added.

Here are a few examples of new terms:

- HP_0410050 Decreased level of 1,5 anhydroglucitol in serum
- HP_0410051 Increased level of 3-hydroxy-3-methylglutaric acid in urine
- HP_0410052 Increased level of allantoin in serum

**Comment by pnrobinson** [comment]
I guess I am on the hook for a beverege then...I will check what is going on...

**Comment by nicolevasilevsky** [comment]
Alternatively, I could just add the annotations directly to the annotation files in Excel. Maybe that would be easier?

**Comment by pnrobinson** [comment]
The autocomplete was not being updated after the local hp.obo import. I have fixed this and tested the function. Please try the new release & close this issue if everything works (it should!)

**Comment by nicolevasilevsky** [comment]
Looks like the fix was to HPOWorkbench. Could you add this fix to PhenoteFX too? :)

![image](https://user-images.githubusercontent.com/6722114/36234621-caa01a5c-11a0-11e8-8e61-3bcd4e603e36.png)

**Comment by pnrobinson** [comment]
I think this is working now!
