### ISSUE TITLE
Modifier and clinical course

### ISSUE THREAD

**Issue by pnrobinson** [pnrobinson/hphenote#66]
We should add autocomplete for clinical course (e.g., episodic) to the Modifier field.

**Comment by pnrobinson** [comment]
Explore using `` Consumer<Main.PhenotypeTerm> addHook`` for a second hook.
We can done something like this to get the selected row of the table
```
PhenoRow row = tableview.getSelectionModel().getSelectedItem();
```
We then check whether the term that is currently selected in the ontology tree is valid for the Modifier column. If so, we modify the PhenoRow by adding that modifier, and then we refresh the table view.

@kingmanzhang  do you think this would work?
I guess we would need to modify some code in HpoTextMiner? @ielis

**Comment by kingmanzhang** [comment]
Yes, that sounds a feasible solution. However, maybe we can keep the current HpoTextMiner unchanged by passing a different hook when you click "update" in modifier column.

**Comment by kingmanzhang** [comment]
Another comment is if you use observable map to store data, there is no need to create or call refresh_table. It will refresh automatically.

**Comment by pnrobinson** [comment]
implemented
