### ISSUE TITLE
omit incorrect phenotypes from text mining

### ISSUE THREAD

**Issue by kingmanzhang** [pnrobinson/hphenote#67]

**Comment by pnrobinson** [comment]
We should probably add a file somewhere like omit-list.txt called omit-from-mining.txt
@drseb if we have a file with these two columns, then your pipeline would be able not to annotate to these terms, correct? If so, we could add some function to PhenoteFX to allow the curator to easily enter these terms.
There would be a button called ``Add mistaken annotation to omit list`` and this would be a right click on the term name in the table (for instance). It should be easy to implement. Would this work on your side?
```
#OMIM.id   HPO.id
```

**Comment by iamkoehler** [comment]
please also add if this omit-annotation is a positive or negative annotation.

**Comment by pnrobinson** [comment]
I think this was implemented
