### ISSUE TITLE
Cannot open by MIM number in PhenoteFX

### ISSUE THREAD

**Issue by nicolevasilevsky** [pnrobinson/hphenote#75]
On my Mac OS v10.14.3, I cannot open by MIM number in PhenoteFX

**Comment by pnrobinson** [comment]
I think we need to revise the fx shortcuts 
according to Stackoverflow, the following is cross-platform
```
<MenuItem mnemonicParsing="false" text="%menu.save" accelerator="Shortcut+S"/>
```

**Comment by pnrobinson** [comment]
I have found this
```
https://docs.oracle.com/javafx/2/api/javafx/scene/input/KeyCombination.html#SHORTCUT_DOWN
```
and changed the accelerators correspondingly. It should now be platform independent. Also remove the shortcuts from the fxml file.
