### ISSUE TITLE
Cannot resize or scroll through PhenoteFX on laptop screen

### ISSUE THREAD

**Issue by LCCarmody** [pnrobinson/hphenote#77]
I am trying to add 'fetal macrosomia' using the latest PhenoteFX.  I can identify the term I want to use as shown in the screen shot, but I cannot scroll down to the source field.  I had to add the term without this information.

Issues with that are:
1. When adding a term this way, it switches to the actual label name (I was inadvertently adding a synonym). Because the date information is gone and I cannot scroll or move the field that looks like it has the BIocurator info. I wasn't quite sure if the term I wanted to add was there.
2. I could not add the term from the right HPO tree because that search engine doesn't look up synonyms.  

Thanks for making progress on this app, but there needs to be a bit more work if a person is not using the big screen.  Also, could we make the search the same in both 'HPO term' and HPO tree browser?  Because it is a small screen, it is not terribly convenient to jump back to the hpo site or even protege.  I do for some things but it would be nice if I didn't have to do it.
Thanks.

<img width="1349" alt="Screen Shot 2019-05-24 at 1 06 58 PM" src="https://user-images.githubusercontent.com/26067008/58344884-ebb5e680-7e24-11e9-966c-c6ee7cfe6ab8.png">

**Comment by LCCarmody** [comment]
Also, are we unable to edit the biocuration? It doesn't work on mine.

**Comment by kingmanzhang** [comment]
The resizing issue should be solved in the new release.

**Comment by kingmanzhang** [comment]
All requests should be addressed in the next release.
