### ISSUE TITLE
Installing initial files to somewhere other than home directory

### ISSUE THREAD

**Issue by travisbickle34** [pnrobinson/hphenote#83]
Hi,

Is there a way to prevent the initial downloads of MedGen HPO OMIM and HPO going to my home directory?

This doesn't appear to be controlled by the default download directory setting and I am suffering from issues due to very limited space in my home directory.

Any help appreciated!

**Comment by pnrobinson** [comment]
At present, the settings are hard-coded to be written to the home directory, I believe. However, the files are not that big, a few tens of MB. Are you sure this is the issue?

**Comment by travisbickle34** [comment]
It is.  Our home dirs are set up to be ridiculously small.

However, the user I am contacting you on behalf of should be able to free up some space.

The fact that it is hardcoded essentially answers my question and gives me all I need to know.

Thanks a lot for the prompt response, Peter!

Best,

Gavin

**Comment by pnrobinson** [comment]
OK, please reopen if things do not work out!
