### ISSUE TITLE
Issues with saving/loading MONDO files

### ISSUE THREAD

**Issue by LCCarmody** [pnrobinson/hphenote#84]
I am not sure what is going on--suspect this is due to some system update.
However, yesterday, I tried to curate a diseases (primarily alzheimers and parkinsons).  I *thought* I saved at least 2 files, but I could only find one today. It will not open in PhenoteFX and opening in a text editor revealed only general phenotype annotations but none of the risk factor info.

So, I tried to start again today, and now PhenoteFX cannot find MONDO files. Created a new one, but it didn't save.  Decided to restart computer and start the system again--including downloading Mondo.  I ended up with this error message:  
![Screen Shot 2019-09-18 at 11 44 45 AM](https://user-images.githubusercontent.com/26067008/65165233-5dd1bd00-da0c-11e9-934e-3c2e07b7528d.png)

**Comment by pnrobinson** [comment]
This issue has gotten stale, closing.
