### ISSUE TITLE
Could not find or load main class org.monarchinitiative.phenotefx.PhenoteFX

### ISSUE THREAD

**Issue by timjeske** [pnrobinson/hphenote#89]
Dear developers of PhenoteFX,

we find PhenoteFX very exciting and would love to install it. Unfortunately, we get the same error over and over again:

`Error: Could not find or load main class org.monarchinitiative.phenotefx.PhenoteFX`

I've downloaded the JAR file of release v0.5.0 and try to run it with the following command:

`java -jar PhenoteFX.jar --module-path /data/Software/javafx-sdk-11.0.2/lib --add-modules javafx.controls`

I'm using the following Java version:

`openjdk version "1.8.0_212"`
`OpenJDK Runtime Environment (build 1.8.0_212-b04)`
`OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)`

I'm not sure what might be wrong and would be very thankful for any help!

Best regards
Tim

**Comment by pnrobinson** [comment]
Hi Tim,
we wrote PhenoteFX for our internal use in curating for HPO. You are welcome to use it, but if you are planning on curating please get in touch with me and maybe there is some way you could contribute to the HPO data.
As far as I know, PhenoteFX currently will only run on Oracle Java 8. (OpenJDK does not contain javaFX, and I think we would need to compile it using Java 11/modules to use the above lib). It is probably not incredibly difficult to refactor to Java 11, let me know if you are interested in working on that.

**Comment by timjeske** [comment]
Hi Peter, 

thank you very much for your quick reply! My teammate is already in contact with you to discuss our plans for HPO annotation/curation. We could then discuss it in this context.

Best
Tim
